---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
