---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: geerlingguy/docker-centos8-ansible
    pre_build_image: true
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ~/vault_password.txt
verifier:
  name: ansible
lint: |
  set -e
  find . -name "*.yml" ! -name vault.yml -exec yamllint {} \;
  find . -name "*.yml" ! -name vault.yml -exec ansible-lint {} \;
