---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - vault.yml
  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true
  - name: Verify ansible user
    ansible.builtin.command:
      cmd: ls
      argv:
        - /home/ansible
