- name: Create Data Store
  hosts: directory_servers
  gather_facts: no
  tasks:
    - name: Check if Data Store exists
      become_user: dsa
      become_flags: "-i"
      shell: "dxserver status | grep crausers"
      register: datastore
      ignore_errors: true
    - name: Create Data Store
      become_user: dsa
      # Loading environment variables set: become_flags
      become_flags: "-i"
      shell: "chdir=/disk/apps/directory/dxserver/bin ./dxnewdsa crausers 389 \"ou=People,o=cra\""
      when: datastore['rc'] != 0