- name: Create ansible user
  hosts: directory_servers
  gather_facts: no
  remote_user: iacpocadmin
  vars:
     ansible_ssh_private_key_file: ~/iacpocadmin_key/id_rsa.pem
  tasks:
    - name: Create user
      user:
        name: ansible
        create_home: yes
        group: adm
        uid: 1041

- name: Create SSH key
  hosts: localhost
  gather_facts: no
  become: false
  tasks:
    - name: Remove existing private key file
      file:
        path: ~/.ssh/id_rsa
        state: absent
    - name: Create SSH key
    # Generate SSH key without passphrase
      command: ssh-keygen -f ~/.ssh/id_rsa -N ''
      
- name: Copy public key to directory_servers
  hosts: directory_servers
  gather_facts: no
  remote_user: iacpocadmin
  vars:
     ansible_ssh_private_key_file: ~/iacpocadmin_key/id_rsa.pem
  tasks:
    - name: copy over SSH public key to remote machine
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    - name: Add sudoers permission
      copy:
        content: "ansible ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root

