---
- name: Uninstall CA Directory
  hosts: directory_servers
  gather_facts: no
  tasks:
    - name: Check dsa user
      command: "id dsa"
      register: iddsa
      ignore_errors: true
    - name: Uninstallation
      block:
        - name: Uninstall CA Directory
          command: chdir=/disk/apps/directory/dxserver/uninstall ./dxuninst.sh -silent
        - name: Check dsa user
          command: "id dsa"
          register: iddsa
          ignore_errors: true
        - name: Check if Uninstallation is sucessful
          fail: 
            msg: Installation failed.
          when: iddsa['rc'] != 0
      when: iddsa['rc'] == 0