---
- name: Uninstall CA Directory
  gather_facts: false
  hosts: directory_servers
  tasks:
    - name: Check for dsa user.
      command: id dsa
      register: iddsa
    - name: uninstall CA Directory
      become_method: su
      shell: /disk/apps/directory/dxserver/uninstall/dxuninst.sh -silent
      when: iddsa['rc'] == 0 ## dsa user exists i.e. directory is installed
