---
- name: Install openldap-clients
  ansible.builtin.yum:
    name: openldap-clients
- name: Copy and replace password placeholder in admin.ldif
  ansible.builtin.template:
    src: "admin.ldif"
    dest: "~/admin.ldif"
    # owner: "ansible"
    # group: "adm"
    mode: '0600'
- name: Search for Admin user
  ansible.builtin.command: ldapsearch -H ldap://{{ansible_hostname}}:4000 -x -b "cn=admin,ou=People,o=cra"
  register: search_result
  ignore_errors: true
  changed_when: false
- name: Make sure we have an admin user
  ansible.builtin.command: "ldapadd -H ldap://{{ansible_hostname}}:4000 -x -f ~/admin.ldif"
  # with_items: "{{ groups['directory_servers'] }}"
  register: admin_user_result
  changed_when: true
  when: search_result["rc"] == 32 # if admin user doesn't exist