---
- name: Copy custom_x500.dxc
  ansible.builtin.template:
    src: files/x500.dxc
    dest: /disk/apps/directory/dxserver/config/schema/x500.dxc
    owner: dsa
    group: dsa
    mode: 0440
  notify: Reload configurations
