---
- name: Check dsa user
  ansible.builtin.command:  
    argv:
      - id 
      - dsa
  register: iddsa
  ignore_errors: true
  changed_when: false
- name: Installation
  when: iddsa['rc'] != 0 # dsa user doesn't exist
  block:
    - name: Create directory
      ansible.builtin.file:
        path: /home/ansible/ca_directory
        state: directory
        mode: '0644'
    - name: Copy response file
      ansible.builtin.template:
        src: "response_file"
        dest: "/home/ansible/ca_directory/response_file"
        owner: "ansible"
        group: "adm"
        mode: 0600
    - name: Unarchive .tar.gz file
      ansible.builtin.unarchive:
        src: /tmp/SymantecDirectoryServerLinux64bit_r14.1SP4_IMS_Only.tar.gz
        dest: /home/ansible/ca_directory
    - name: Install CA Directory
      ansible.builtin.command:
        argv: 
          - ./dxsetup.sh
          - -silent 
          - -responsefile 
          - /home/ansible/ca_directory/response_file
        chdir: /home/ansible/ca_directory/dxserver/install/
      changed_when: true