- name: Load an ldif file
  vars_files:
    - ~/secret.yml
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Load users from a ldif file
      command: "ldapadd -H ldap://{{ item }}:4000 -D \"cn=admin,ou=People,o=cra\" -w {{ LDAP_ADMIN_PASSWORD }} -f ../files/data.ldif"
      loop: "{{ groups['directory_servers'] }}"
      register: user_result
      ignore_errors: true
      changed_when: true
    - name: Fail if return code is not 0 or 68 (user already exists)
      fail:
        msg: Failed to create admin user
      when: item['rc'] != 0 and item['rc'] != 68
      loop: "{{ user_result.results }}"
