---
# tasks file for ca_directory
- ansible.builtin.import_tasks: install_ca_directory.yml
- ansible.builtin.import_tasks: start_ca_directory.yml
- ansible.builtin.import_tasks: create_dsa.yml
- ansible.builtin.import_tasks: start_dsa.yml
- ansible.builtin.import_tasks: create_ldap_admin_user.yml
- ansible.builtin.import_tasks: load_users.yml