- name: Start dsa
  hosts: directory_servers
  become: true
  become_user: dsa
  become_flags: "-i"
  gather_facts: false
  tasks:
    - name: Start dsa
      command: dxserver start all
      changed_when: false
